### ISSUE TITLE
Please remove the pc- prefix from the repository's name

### ISSUE THREAD

**Issue by cyyynthia** [Bri-ish/copy-std-msg-url#1]
Hello, Powercord developer here.

Since you don't seem to be in our Discord server, I'll ask here: the pc- prefix is reserved for internal plugin and should not be used by any third party plugin made. If you could please rename your repository to remove this (by using powercord- for example) it'd be very appreciated.

Thank you!

**Comment by BlameBurr** [comment]
Apologies, didn't realise it was a reserved prefix, I've renamed the repository and because I'd forgotten to update my Discord it's `Bri-ish#0001.`
Thank you :)
